### ISSUE TITLE
NPC Issues

### ISSUE THREAD

**Issue by ItsKodas** [ItsKodas/Horizons-Universe#7]
We'll need to further investigate crashes and session lag causes during the open beta to determine whether or not certain NPC's are causing the server to mass lag and crash.

**Comment by ItsKodas** [comment]
Physics peaked at 60ms<, most likely caused by NPC hitting voxels.
Best bet would be to discover which NPC mod is chucking ships into planets.

In Season 2 we discovered that REAVERS were flying directly into planets and not deleting, may be worth while removing them from planet based systems and only adding them to systems that do not have planets.

Further investigation is required.

**Comment by lukeypookie111** [comment]
Could this be fixed by adjusting clean up setting?

**Comment by ItsKodas** [comment]
It would be a band-aid unfortunately, as it would also delete all other NPC's and blocks owned by nobody...

**Comment by lukeypookie111** [comment]
In Season 2 we discovered that REAVERS were flying directly into planets and not deleting, may be worth while removing them from planet based systems and only adding them to systems that do not have planets.

this is proboly the best solution

**Comment by lukeypookie111** [comment]
![image](https://user-images.githubusercontent.com/69785730/130895424-cb52190d-34f7-4e78-bbe6-0cea03819332.png)

maybe adjust the threat levels if possible so they start spawning once you are actually big enough

**Comment by lukeypookie111** [comment]
![image](https://user-images.githubusercontent.com/69785730/130897162-650bf02e-8dba-4a42-bc6e-4341e49685b4.png)

both SEMS AND IMBER are on ground colliding also they are fighting

**Comment by ItsKodas** [comment]
Decreased NPC Spawn Rate to 1 - 2 rather than 15+, we'll see how it goes

**Comment by ItsKodas** [comment]
Factions `SEMS` & `IMDC` has a tendency to kamakazi causing mass lag however changes to Spawn Rates have improved performance.
We'll need to identify the exact mod/s that controls these factions and test performance after removal of them.
Players are currently pointing towards `Faction Wars` as they are attacking each other which leads to them smashing into the ground.

On another note it seems that some factions are not spawning with an owner.

- [x] Test Removal of `Faction Wars`
- [x] Fix NPCs crashing into voxels
- [x] Fix certain faction/s not spawning with owners

**Comment by ItsKodas** [comment]
<ModItem FriendlyName="More NPC Encounters V7 Faction Wars">
      <Name>2315059547.sbm</Name>
      <PublishedFileId>2315059547</PublishedFileId>
      <PublishedServiceName>Steam</PublishedServiceName>
    </ModItem>

**Comment by ItsKodas** [comment]
NPCs don't seem to be spawning correctly after removing Faction Wars

**Comment by lukeypookie111** [comment]
I believe there is no gravity base npcs spawns available recommend one or more of the following mods (i have check most of them and all seem to not have issues)

[Reddit Custom Encounters](https://steamcommunity.com/sharedfiles/filedetails/?id=445996030)

[Orks: The Great WAAAGH!](https://steamcommunity.com/sharedfiles/filedetails/?id=1793333265)
![image](https://user-images.githubusercontent.com/69785730/131134114-96a50655-59d6-4d0d-b0bd-bc7fe26c9f46.png)

this is a really big mod might have issues due to adding police military trading ect
[EEM] Exploration Enhancement Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=531659576)

[Air traffic](https://steamcommunity.com/sharedfiles/filedetails/?id=973526550) 
sadly this cant be used due to the new ammo and is being overhaul  but will be updated soon

 [Smugglers](https://steamcommunity.com/sharedfiles/filedetails/?id=2384718926)

[CULT Remains](https://steamcommunity.com/sharedfiles/filedetails/?id=2169237583)

[Assertive Cargo Ships](https://steamcommunity.com/sharedfiles/filedetails/?id=1902970975)

![image](https://user-images.githubusercontent.com/69785730/131135090-d66a7757-33e6-4f78-90c3-73b23a4898d0.png)

[Abominations PvE Encounters](https://steamcommunity.com/sharedfiles/filedetails/?id=2388186207)

[Mercenaries PvE Encounters](https://steamcommunity.com/sharedfiles/filedetails/?id=2578712641)

**Comment by lukeypookie111** [comment]
one more thing, have the threat score level been played with?

![image](https://user-images.githubusercontent.com/69785730/131137553-2074f6c6-7ef2-415e-8721-9b9079a749b7.png)

**Comment by ItsKodas** [comment]
Server seems to be capable of handling faction wars, I'm going to try another NPC faction reset to attempt fixing some NPCs spawning without owners but I'll keep faction wars installed unless the server fails to handle it.

**Comment by ItsKodas** [comment]
Some NPCs Spawning without owners has been fixed

**Comment by lukeypookie111** [comment]
after faction war added server performance drops as low at 0.3 sim speed

**Comment by lukeypookie111** [comment]
atleast i think its something to do with factoin wars

**Comment by ItsKodas** [comment]
![image](https://user-images.githubusercontent.com/43526329/131248891-17b10832-65b4-426f-8626-3359c1f439b3.png)
Faction Wars needs to be investigated further

**Comment by lukeypookie111** [comment]
was facton wars removed?
 
part of investigation look at performance from the last 5 mins when i post this, 530 nzt

**Comment by lukeypookie111** [comment]
another though could it just be that the world is slightly corrupts or something which leads to memory leaks, i remeber you saying that i was using like 8 GB of ram after just restarting

**Comment by lukeypookie111** [comment]
big performance drop 6:26am nzt

**Comment by lukeypookie111** [comment]
![image](https://user-images.githubusercontent.com/69785730/131561619-e53c0f9a-8e1d-445b-8bcc-5515e9d7e495.png)
 looking into adjusting settings the above one might help despawn grids that go further away from players

![image](https://user-images.githubusercontent.com/69785730/131565784-ea23a941-9764-46c9-a185-0af434326f49.png)
 i read that this might also be causing issue, the sim speed is tanking when npcs try to spawn, so possibly lowering this might help

i know that i cant recreate the scope of a dedicated server but i have cranked the settings up to 150 in the same area, spawning every minute ect

**Comment by lukeypookie111** [comment]
![image](https://user-images.githubusercontent.com/69785730/131571599-5157a635-a330-4364-8a2a-a4bf69878413.png)

So after investigation of what i could, couldn't find anything on my end but since i am running it on single player doesn't really matter

One idea that we could do is make a creative world and do some testing with the npcs test if it is actually faction wars or is it just npcs overall, if so would changing from a framework such as MES that has other people make mods for, to EEM, its a big mod but its a single mod that is developed by one team/person which means the quality is high and less impact full on the server, this way we could remove npcs from one sector and have it on another to do "long term testing"(is a day long term?), we can also fix the asteroid problem



i really think this would be better it adds something for every one
[EEM](https://steamcommunity.com/sharedfiles/filedetails/?id=531659576)
[to go with EEM](https://steamcommunity.com/sharedfiles/filedetails/?id=1984228576)
might need [this](https://steamcommunity.com/sharedfiles/filedetails/?id=1931509062) to replace the weapons on the npcs 

guessing you already do something like this but might be [usefull](https://steamcommunity.com/sharedfiles/filedetails/?id=2085051314)
I keep seeing the word sync distance and it needing to be greater than 10 k, i assume it is but still going to put this info for reference

**Comment by ItsKodas** [comment]
EEM would be awesome but I'm sure we had it previously and I think it was causing server crashes, I'll have to check with froggie

**Comment by lukeypookie111** [comment]
FUCK

**Comment by lukeypookie111** [comment]
have a look at this https://steamcommunity.com/sharedfiles/filedetails/?id=2085051314

**Comment by ItsKodas** [comment]
yeah I'm gonna add that, looks useful
